version: "3.9"

services:
  admin:
    build:
      context: ./admin
    container_name: admin
    env_file: ./admin/.env
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCOUNT_ID=975391191374 
      - APP_CONFIG_TABLE=YANTECH-YNP01-AWS-appTable-dev
    ports:
      - "8001:8001"

  requestor:
    build:
      context: ./requestor
    container_name: requestor
    env_file: ./requestor/.env
    environment:
      - AWS_REGION=us-east-1
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/975391191374/YANTECH-YNP01-AWS-sqs-notification-requests-dev
      - AWS_ACCOUNT_ID=975391191374 
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./worker
    container_name: worker
    env_file: ./worker/.env
    environment:
      - AWS_REGION=us-east-1
      - APPLICATIONS_TABLE=YANTECH-YNP01-AWS-appTable-dev
      - REQUEST_LOG_TABLE=YANTECH-YNP01-AWS-logsTable-dev  
    restart: on-failure
