name: Build and Push Admin Docker Image
on:
    push:
        paths:
            - 'admin/**'
        branches:
            - main

permissions:
    id-token: write
    contents: read

env:
    AWS_REGION: 'us-east-1'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<OIDC_ROLE_NAME>
                    aws-region: <AWS_REGION>

            - name: Log in to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker image
                run: |
                    docker build -t ${{ env.IMAGE_NAME }} ./admin
                env:
                    IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
                    REPOSITORY_NAME: <ECR_REPOSITORY_NAME>

            - name: Push Docker image to ECR
                run: |
                    docker push ${{ env.IMAGE_NAME }}
                env:
                    IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
                    REPOSITORY_NAME: <ECR_REPOSITORY_NAME>