name: Build and Push Requester Docker Image to ECR

on:
    push:
        paths:
            - 'requestor/**'

env:
    ECR_REPOSITORY_ADMIN : ${{ secrets.ECR_REPOSITORY_ADMIN }} # Ensure this secret is set in your repository settings
    ECR_REPOSITORY_WORKER : ${{ secrets.ECR_REPOSITORY_WORKER }}
    ECR_REPOSITORY_REQUESTER : ${{ secrets.ECR_REPOSITORY_REQUESTER }}
    SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }} # Ensure this secret is set in your repository settings
    ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }} # Ensure this secret is set in your repository settings
    AWS_REGION: us-east-1 # Change to your region
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1 # Change to your region

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker image
              run: |
                  docker build -t ${{ secrets.ECR_REPOSITORY }}:latest ./request

            - name: Tag Docker image
              run: |
                  docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

            - name: Push Docker image to ECR
              run: |
                  docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest